apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.NAME }}-svc"
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  type: ClusterIP
  selector:
    environment: "{{ .Values.NAMESPACE }}"
    app: "{{ .Values.APP }}"
    microservice: "{{ .Values.MICROSERVICE }}"
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  - port: 9300
    targetPort: 9300
    protocol: TCP
  